version: '3.9'

services:
  web:
    build: ./ServerWeb/
    container_name: "web"
    ports:
      - "8080:80"
    networks:
      - db_net
      - auth_net

  authentication:
    build: ./ServerAuth/
    container_name: "authentication"
    expose:
      - "8000"
    networks:
      - auth_net
  
  database:
    build: ./ServerDB/
    container_name: "database"
    expose:
      - "8000"
    networks:
      - db_net

networks:
  db_net:
    driver: bridge
  auth_net:
    driver: bridge
  